apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: village-upload
  name: village-upload
  namespace: village   #一定要写名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: village-upload
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: village-upload
    spec:
      imagePullSecrets:
        - name: harbor-reg  #提前在项目下配置访问harbor的账号密码
      containers:
        - image: $REGISTRY/$ALIYUNHUB_NAMESPACE/village-upload
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: village-upload
  name: village-upload
  namespace: village
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: village-upload
  sessionAffinity: None
  type: ClusterIP